### ISSUE TITLE
.

### ISSUE THREAD

**Issue by graysuit** [gammasoft71/Examples#1]

**Comment by gammasoft71** [comment]
Hi,

Not for the moment, I haven't tested the NDK android yet.

Regards,
Gammasoft

**Comment by graysuit** [comment]
You can try ndk whenever you like and have time.
https://devblogs.microsoft.com/cppblog/android-and-ios-development-with-c-in-visual-studio/
https://youtu.be/3SJmf1HsVQU
https://youtu.be/7U9q1RfLeso

And sample apk:
[MS_VS_android_ndk_sample.apk.zip](https://github.com/gammasoft71/Examples/files/5782017/MS_VS_android_ndk_sample.apk.zip)

Till that you can remain this issue open as todo and also if any contributor see, he can help.
Thanks so much for time. 
Happy coding 
__(-_-)__     <3

**Comment by graysuit** [comment]
One more things,
You can join our cyber security discord group.
I will be happy to have your assistance:
https://discord.com/invite/Hu5XPGMTuk

Your projects took so much time. But I am sad it doesn't have much stars according to effort you did. I will promote your projects.
